language: python
python: ['3.4']

branches:
  only:
  - source

env:
  global:
  - GH_REF: 'github.com/lexi-lambda/lexi-lambda.github.io.git'
  - secure: "cWYfJKfWfn3qSlTX26NpIAC7+HWJc9tsJ2PUNnYNc60CFWBbVf2Srjrtt8CCYOMheA7K/jFNlT/px1+JKzruHMEVuUHFwIV7K8MGzSI5H6Y4gzOEfRMX8QZ/dNBEOJmkaXn70jBjYiefmg9Y20Tc41jppm6/nCb2KAfdUPcj6Hr1yit23BPRbbdf0lKWPFJFdYKk/7433LJbSZryDDBMHNioudn8fpE40ww34lbIb92qdbMEHV/O6N0KyAQMabfcgqGpsLt8VNECJNxnwZi8MBbf6EfyaG8e9XX8fBpdmCJ9K8ShjrpDbBqEmwFH7SowzdfTDu5OMcfc4TdES68G+CwbHG0htdNM9HCgf3XeFDO5gUopepeuCmnoBaZDmsXybTxXB7wt51bk+zz6GOrTfYHn93U82LNRvjFMiiwSOZz9xUC43LRF/dWBDBkpsK9EVA8l1mtoRs+4haZsCtxLs9BYuoGKDmSPU/4doCtDFh1+Lqgca3SNtOa4UwnZrhkSqiUszlqNvJcaEw0fBFsapxEIwFWbQz9A8k+yDgSv1rBmxK9IKnBLxM2LQxEIAZ1tIKfZtAWVu8IDiMF4acticQSwCaRXAE0XSBJ5zbmIshtgJQTVcxb1sefV5IRBbp6NDNIBnVGm+pSTXdMPqbGt8hha/C0xF0Wr9vc9xoti/Ig="
  - RACKET_DIR: '~/racket'
  - RACKET_VERSION: '6.9'

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"

install:
# install a newer version of node than Travis gives us by default
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- source ~/.nvm/nvm.sh
- nvm install v8.1.2
- npm install

# install pygments for highlighting support
- pip install pygments

# install frog
- raco pkg install --no-setup --auto frog
- raco setup -D --pkgs frog

script: bash ./deploy.sh
